# Generated by Django 5.0 on 2023-12-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_emp_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
