# Generated by Django 5.0 on 2023-12-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_emp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
