# Generated by Django 5.0 on 2024-01-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_alter_emp_pimage_alter_emp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
